#!/usr/bin/env python
# coding: utf-8

"""
This Python script can read a depth.txt file generated by the depth function of samtools. A total of 24 line graphs will be generated 
in a 8x3 format showing the sequencing depth across the position of each human chromosome.
""" 

import pandas as pd
import matplotlib.pyplot as plt

def author():
    return "Shuqi_E_Wang"

def plot_coverage():
    # Load the data
    coverage_data = pd.read_csv("depth.txt", sep="\t", names=["chromosome", "position", "depth"])
    
    # Get the list of unique chromosomes
    chromosomes = coverage_data['chromosome'].unique()
    
    # Create a figure with subplots (8x3 grid)
    fig, axes = plt.subplots(8, 3, figsize=(20, 20))
    axes = axes.flatten()  # Flatten the axes array for easy indexing
    
    # Plot each chromosome in a separate subplot
    for i, chrom in enumerate(chromosomes): # enumerate() add a counter from 0 to 23 to each chromosone name 
        chrom_data = coverage_data[coverage_data['chromosome'] == chrom]
        ax = axes[i]
        ax.plot(chrom_data['position'], chrom_data['depth'], label=chrom)
        ax.set_title(chrom)
        ax.set_xlabel('Position')
        ax.set_ylabel('Depth')
        ax.legend()
    
    # Adjust layout to prevent overlap
    plt.tight_layout()
    plt.savefig('coverage_chromosome.png')

if __name__ == "__main__":
    print(author())
    plot_coverage()
